<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>ExtensionTemplate</RootNamespace>
        <AssemblyName>ExtensionTemplate</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="YesserCalculator.Extension" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include=".template.config\template.json" />
    </ItemGroup>

</Project>
