<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>YesserCalculator.BaseOperations</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\YesserCalculator.Extension\YesserCalculator.Extension.csproj" />
    </ItemGroup>

</Project>
